### PR TITLE
galaxy s6 cases

### PR DESCRIPTION
**Pull request by atkins**

### CODE REVIEW

**Comment by hoelzro** [comment]
@atkins By the way, there's a test in shuttle called `test_android_case_orders` that, iirc, throws live orders at the test endpoint.  It should be easy to add new case IDs in there for testing.

**Comment by atkins** [comment]
Ahh, good to know, I'll update that!

**Comment by jmelvnsn** [comment]
Hi everyone! I'm still on this repo?

**Comment by hoelzro** [comment]
Hi @jmelvnsn!  How's life?

**Pull request merged**
